update

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -33,7 +33,7 @@ jobs:
         run: go install fyne.io/tools/cmd/fyne@latest
       - name: Build and package Linux app
         run: |
-          if [ ! -f "${{ env.ICON_PATH }}" ]; then touch ${{ env.ICON_PATH }}; fi
+          if [ ! -f "${{ env.ICON_PATH }}" ]; then echo "Icon file not found"; exit 1; fi
           # 简化：不指定 -os，让工具在原生环境 (linux/amd64) 中自动构建
           fyne package --app-id ${{ env.APP_ID }} --icon ${{ env.ICON_PATH }} --name ${{ env.PROJECT_NAME }} -src ${{ env.CMD_PATH }}
           mv ./${{ env.PROJECT_NAME }}.tar.xz ./${{ env.PROJECT_NAME }}-linux-amd64.tar.xz
@@ -59,7 +59,7 @@ jobs:
       - name: Build and package Windows app
         shell: powershell
         run: |
-          if (!(Test-Path "${{ env.ICON_PATH }}")) { New-Item -ItemType File -Path "${{ env.ICON_PATH }}" }
+          if [ ! -f "${{ env.ICON_PATH }}" ]; then echo "Icon file not found"; exit 1; fi
           # 简化：不指定 -os，让工具在原生环境 (windows/amd64) 中自动构建
           fyne package --app-id ${{ env.APP_ID }} --icon ${{ env.ICON_PATH }} --name ${{ env.PROJECT_NAME }} -src ${{ env.CMD_PATH }}
           Rename-Item -Path "${{ env.PROJECT_NAME }}.zip" -NewName "${{ env.PROJECT_NAME }}-windows-amd64.zip"
@@ -91,7 +91,8 @@ jobs:
         run: go install fyne.io/tools/cmd/fyne@latest
       - name: Build and package macOS app
         run: |
-          if [ ! -f "${{ env.ICON_PATH }}" ]; then touch ${{ env.ICON_PATH }}; fi
+          if [ ! -f "${{ env.ICON_PATH }}" ]; then echo "Icon file not found"; exit 1; fi
+          export MACOSX_DEPLOYMENT_TARGET=10.14
           # 简化：不指定 -os，让工具在原生环境 (darwin/amd64 或 darwin/arm64) 中自动构建
           fyne package --app-id ${{ env.APP_ID }} --icon ${{ env.ICON_PATH }} --name ${{ env.PROJECT_NAME }} -src ${{ env.CMD_PATH }}
           mv ./${{ env.PROJECT_NAME }}.zip ./${{ env.PROJECT_NAME }}-macos-${{ matrix.name_suffix }}.zip
